In [1]:
import numpy as np

#### numpy.ones
* numpy.ones(shape, dtype=None, order='C', *, like=None)

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [4]:
np.ones((2,1), dtype = int)

array([[1],
       [1]])

In [5]:
k = np.ones((2,3))

In [6]:
k.ndim

2

In [7]:
k*3

array([[3., 3., 3.],
       [3., 3., 3.]])

#### numpy.zeros
* numpy.zeros(shape, dtype=float, order='C', *, like=None)



In [8]:
np.zeros((2,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### numpy.ones_like
* numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)
```
numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None):ones_like 함수는 주어진 배열과 같은 shape과 dtype을 가지는 배열을 생성합니다. 주어진 배열과 동일한 모양으로 1로 채워진 배열을 만듭니다.
a는 기존의 배열입니다. 이 배열과 동일한 모양과 데이터 타입을 가진 배열을 생성합니다. a는 NumPy 배열이어야 합니다.
dtype, order, subok, shape 등의 인수는 ones 함수와 동일하게 작동합니다.

```작동함.

In [9]:
arr1 = np.array([[2,3,4],[5,6,7]])
ones_like_arr = np.ones_like(arr1)
print(ones_like_arr)

[[1 1 1]
 [1 1 1]]


#### numpy.zeros_like
* numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

In [10]:
arr1 = np.array([[2,3,4],[5,6,7]])
ones_like_arr = np.zeros_like(arr1)
print(ones_like_arr)

[[0 0 0]
 [0 0 0]]


#### 대입연산자와 copy의 차이

In [13]:
# 대입연산자
a = [[1,2,3],[5,6,7]]
b = np.array(a)

In [14]:
b

array([[1, 2, 3],
       [5, 6, 7]])

In [17]:
b[1][0] = 100
b

array([[  1,   2,   3],
       [100,   6,   7]])

#### copy 연산자
* np.copy(a, copy = True)
* '변수명'.copy()

In [20]:
# copy 연산자
a = np.array([[1, 2, 3],[5, 6, 7]])
c = a.copy()
c

array([[1, 2, 3],
       [5, 6, 7]])

* copy연산자를 주로 사용
  => 새로운 인스턴스를 만들고,인스턴스의 값만 복사
  => 두 공간의 메모리가 서로 다름.(=> 다른 객체임.)

In [21]:
a = np.array([[1, 2, 3],[5, 6, 7]])
d = np.copy(a)
d

array([[1, 2, 3],
       [5, 6, 7]])

In [22]:
a = np.array([[1, 2, 3],[5, 6, 7]])
e = np.array(a, copy=True)
e

array([[1, 2, 3],
       [5, 6, 7]])

* 파이썬은 객체 지향적 프로그램
* 객체 지향적 프로그램 : 객체를 생성 시킨 후 새로운 변수에 저장하는 방법
* 인스턴스 : 객체 안에 있는 `attributes`와 매소드를 사용할 수 있게 하는 방법
* 객체 : 인스턴스가 들어있는 변수
* 모든 변수를 저장하면 인스턴스가 생성됨.

In [24]:
a = np.array([[1, 0, 0, 0],
             [0, 1, 0, 0],
             [0, 0, 1, 0],
             [0, 0, 0, 1]])

#### IDENTITY ARRAY
* 단위 행렬
* numpy.identity(n, dtype = None, *, like=None)

In [25]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### eye function
* numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [28]:
f = np.eye(5, 8, k=1)

In [30]:
f

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

* a

* argmin, argmax

In [34]:
A = np.array([5, 2, 3, 1, 100, 2])
A.argmax()
A.argmin()

3

* 홀수 인덱스로 구성된 새 배열을 생성

In [36]:
a = np.array([1, 2, 5, 6, 10, 12, 21, 40])
a

array([ 1,  2,  5,  6, 10, 12, 21, 40])

In [39]:
a[1::2]

array([ 2,  6, 12, 40])

In [38]:
np.where(a % 2 == 0)

(array([1, 3, 4, 5, 7], dtype=int64),)

* 역순 배열

In [41]:
a[::-1]

array([40, 21, 12, 10,  6,  5,  2,  1])

In [49]:
# 각 행의 요소가 역순인 m에서 새 배열
m = np.array([ [11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
m[::,::-1]

array([[14, 13, 12, 11],
       [24, 23, 22, 21],
       [34, 33, 32, 31]])

In [50]:
m[::-1]

array([[31, 32, 33, 34],
       [21, 22, 23, 24],
       [11, 12, 13, 14]])

In [51]:
m[::-1, ::-1]

array([[34, 33, 32, 31],
       [24, 23, 22, 21],
       [14, 13, 12, 11]])

In [55]:
m[0::2][::-1, ::-1]

array([[34, 33, 32, 31],
       [14, 13, 12, 11]])

#### Data Type Objects, DTYPE
* numpy.dtype(dtype, align=False, copy=False[, metadata])

In [56]:
i16 = np.dtype(np.int16)
print(i16)

int16


In [61]:
lst = [[3.4, 8.7, 9.9],[1.1, -7.8, -0.7], [4.1, 12.3, 4.8]]
np.array(lst, dtype = i16)

array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int16)

#### Structured  Arrays

In [66]:
# np.dtype([('문자열', np.int)])
dt = np.dtype([('density', np.int32)])
x = np.array([(393,), (337,), (256,)], dtype = dt)
x

array([(393,), (337,), (256,)], dtype=[('density', '<i4')])

In [68]:
x['density']

array([393, 337, 256])

In [81]:
dt = np.dtype([('density', np.int32), ('margin', np.float64)])
x = np.array([(393,200), (337,300), (256,400)], dtype = dt)
x

array([(b'', 200.), (b'', 300.), (b'', 400.)],
      dtype=[('density', 'S'), ('margin', '<f8')])

In [73]:
x['margin']

array([200., 300., 400.])

In [100]:
dt = np.dtype([('country',np.unicode_, 20), ('density', np.int16), ('area', np.float32), ('population', np.int32)])
x = np.array([('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813),
('Ireland', 65, 70280, 4581269),
('Sweden', 20, 449964, 9515744),
('Finland', 16, 338424, 5410233),
('Norway', 13, 385252, 5033675)],dtype = dt)

In [101]:
x['country']

array(['Netherlands', 'Belgium', 'United Kingdom', 'Germany',
       'Liechtenstein', 'Italy', 'Switzerland', 'Luxembourg', 'France',
       'Austria', 'Greece', 'Ireland', 'Sweden', 'Finland', 'Norway'],
      dtype='<U20')

In [104]:
dt = np.dtype([('country','U20'), ('density', np.int16), ('area', np.float32), ('population', np.int32)])
x = np.array([('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813),
('Ireland', 65, 70280, 4581269),
('Sweden', 20, 449964, 9515744),
('Finland', 16, 338424, 5410233),
('Norway', 13, 385252, 5033675)],dtype = dt)

In [105]:
x['country']

array(['Netherlands', 'Belgium', 'United Kingdom', 'Germany',
       'Liechtenstein', 'Italy', 'Switzerland', 'Luxembourg', 'France',
       'Austria', 'Greece', 'Ireland', 'Sweden', 'Finland', 'Norway'],
      dtype='<U20')

#### 구조화된 배열의 입력 및 출력

In [109]:
# np.savetxt()
# numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
np.savetxt('population_table.csv',
          x, 
            fmt="%s;%d;%d;%d",
           delimiter = ',',
           comments = "#data",
           encoding = "utf8"
          )

#### numpy.genfromtxt
```
numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#',
delimiter=None, skip_header=0, skip_footer=0,
converters=None, missing_values=None, filling_values=None,
usecols=None, names=None, excludelist=None,
deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_',
autostrip=False, case_sensitive=True, defaultfmt='f%i',
unpack=None,
usemask=False,
loose=True,
invalid_raise=True,
max_rows=None, encoding='bytes', *, ndmin=0, like=None)
```

In [110]:
dt = np.dtype([('country','U20'), ('density', 'i4'), 
               ('area', np.float32), ('population', 'i4')])
np.genfromtxt('population_table.csv',
             dtype = dt,
             delimiter = ';',
              encoding = 'UTF8'
             )

array([('Netherlands', 393, 4.15260e+04, 16928800),
       ('Belgium', 337, 3.05100e+04, 11007020),
       ('United Kingdom', 256, 2.43610e+05, 62262000),
       ('Germany', 233, 3.57021e+05, 81799600),
       ('Liechtenstein', 205, 1.60000e+02,    32842),
       ('Italy', 192, 3.01230e+05, 59715625),
       ('Switzerland', 177, 4.12900e+04,  7301994),
       ('Luxembourg', 173, 2.58600e+03,   512000),
       ('France', 111, 5.47030e+05, 63601002),
       ('Austria',  97, 8.38580e+04,  8169929),
       ('Greece',  81, 1.31940e+05, 11606813),
       ('Ireland',  65, 7.02800e+04,  4581269),
       ('Sweden',  20, 4.49964e+05,  9515744),
       ('Finland',  16, 3.38424e+05,  5410233),
       ('Norway',  13, 3.85252e+05,  5033675)],
      dtype=[('country', '<U20'), ('density', '<i4'), ('area', '<f4'), ('population', '<i4')])

In [111]:
time_type = np.dtype( np.dtype([('time', [('h', int), ('min', int), ('sec', int)]),('temperature', float)] ))
times = np.array( [((11, 42, 17), 20.8), ((13, 19, 3), 23.2) ], dtype=time_type)

In [114]:
times

array([((11, 42, 17), 20.8), ((13, 19,  3), 23.2)],
      dtype=[('time', [('h', '<i4'), ('min', '<i4'), ('sec', '<i4')]), ('temperature', '<f8')])

In [117]:
times['time']

array([(11, 42, 17), (13, 19,  3)],
      dtype=[('h', '<i4'), ('min', '<i4'), ('sec', '<i4')])

In [118]:
times['time']['h']

array([11, 13])

In [119]:
times['temperature']

array([20.8, 23.2])

In [122]:
import pickle
lines = open('cities_and_times.txt').readlines()
lines

['Chicago Sun 01:52\n',
 'Columbus Sun 02:52\n',
 'Riyadh  Sun 10:52\n',
 'Copenhagen  Sun 08:52\n',
 'Kuwait City Sun 10:52\n',
 'Rome    Sun 08:52\n',
 'Dallas  Sun 01:52\n',
 'Salt Lake City  Sun 01:52\n',
 'San Francisco Sun 00:52\n',
 'Amsterdam Sun 08:52\n',
 'Denver Sun 01:52\n',
 'San Salvador Sun 01:52\n',
 'Detroit Sun 02:52\n',
 'Las Vegas Sun 00:52\n',
 'Santiago    Sun 04:52\n',
 'Anchorage Sat 23:52\n',
 'Ankara Sun 10:52\n',
 'Lisbon  Sun 07:52\n',
 'S찾o Paulo   Sun 05:52\n',
 'Dubai   Sun 11:52\n',
 'London  Sun 07:52\n',
 'Seattle Sun 00:52\n',
 'Dublin  Sun 07:52\n',
 'Los Angeles Sun 00:52\n',
 'Athens  Sun 09:52\n',
 'Edmonton Sun 01:52\n',
 'Madrid  Sun 08:52\n',
 'Shanghai Sun 15:52\n',
 'Atlanta Sun 02:52\n',
 'Frankfurt   Sun 08:52\n',
 'Singapore Sun 15:52\n',
 'Auckland Sun 20:52\n',
 'Halifax Sun 03:52\n',
 'Melbourne Sun 18:52\n',
 'Stockholm   Sun 08:52\n',
 'Barcelona   Sun 08:52\n',
 'Miami   Sun 02:52\n',
 'Minneapolis Sun 01:52\n',
 'Sydney Sun 18:52\n'

In [135]:
cities = []
for line in lines:
    *city, day, times = line.split()
    hours, minutes = times.split(':')
    print(" ".join(city))
    cities.append((" ".join(city), day, (int(hours), int(minutes))))

fh = open("cities_and_times.pkl", "bw")
pickle.dump(cities, fh)

Chicago
Columbus
Riyadh
Copenhagen
Kuwait City
Rome
Dallas
Salt Lake City
San Francisco
Amsterdam
Denver
San Salvador
Detroit
Las Vegas
Santiago
Anchorage
Ankara
Lisbon
S찾o Paulo
Dubai
London
Seattle
Dublin
Los Angeles
Athens
Edmonton
Madrid
Shanghai
Atlanta
Frankfurt
Singapore
Auckland
Halifax
Melbourne
Stockholm
Barcelona
Miami
Minneapolis
Sydney
Beirut
Helsinki
Montreal
Berlin
Houston
Moscow
Indianapolis
Boston
Tokyo
Brasilia
Istanbul
Toronto
Vancouver
Brussels
Jerusalem
New Orleans
Vienna
Bucharest
Johannesburg
New York
Warsaw
Budapest
Oslo
Washington DC
Ottawa
Winnipeg
Cairo
Paris
Calgary
Kathmandu
Philadelphia
Zurich
Cape Town
Phoenix
Prague
Casablanca
Reykjavik


In [133]:
cities

[('Chicago', 'Sun', (1, 52)),
 ('Columbus', 'Sun', (2, 52)),
 ('Riyadh', 'Sun', (10, 52)),
 ('Copenhagen', 'Sun', (8, 52)),
 ('Kuwait City', 'Sun', (10, 52)),
 ('Rome', 'Sun', (8, 52)),
 ('Dallas', 'Sun', (1, 52)),
 ('Salt Lake City', 'Sun', (1, 52)),
 ('San Francisco', 'Sun', (0, 52)),
 ('Amsterdam', 'Sun', (8, 52)),
 ('Denver', 'Sun', (1, 52)),
 ('San Salvador', 'Sun', (1, 52)),
 ('Detroit', 'Sun', (2, 52)),
 ('Las Vegas', 'Sun', (0, 52)),
 ('Santiago', 'Sun', (4, 52)),
 ('Anchorage', 'Sat', (23, 52)),
 ('Ankara', 'Sun', (10, 52)),
 ('Lisbon', 'Sun', (7, 52)),
 ('S찾o Paulo', 'Sun', (5, 52)),
 ('Dubai', 'Sun', (11, 52)),
 ('London', 'Sun', (7, 52)),
 ('Seattle', 'Sun', (0, 52)),
 ('Dublin', 'Sun', (7, 52)),
 ('Los Angeles', 'Sun', (0, 52)),
 ('Athens', 'Sun', (9, 52)),
 ('Edmonton', 'Sun', (1, 52)),
 ('Madrid', 'Sun', (8, 52)),
 ('Shanghai', 'Sun', (15, 52)),
 ('Atlanta', 'Sun', (2, 52)),
 ('Frankfurt', 'Sun', (8, 52)),
 ('Singapore', 'Sun', (15, 52)),
 ('Auckland', 'Sun', (20, 52)),


In [143]:
with open('cities_and_times.pkl', 'rb') as pl:
    a = pickle.load(pl)
a

[('Chicago', 'Sun', (1, 52)),
 ('Columbus', 'Sun', (2, 52)),
 ('Riyadh', 'Sun', (10, 52)),
 ('Copenhagen', 'Sun', (8, 52)),
 ('Kuwait City', 'Sun', (10, 52)),
 ('Rome', 'Sun', (8, 52)),
 ('Dallas', 'Sun', (1, 52)),
 ('Salt Lake City', 'Sun', (1, 52)),
 ('San Francisco', 'Sun', (0, 52)),
 ('Amsterdam', 'Sun', (8, 52)),
 ('Denver', 'Sun', (1, 52)),
 ('San Salvador', 'Sun', (1, 52)),
 ('Detroit', 'Sun', (2, 52)),
 ('Las Vegas', 'Sun', (0, 52)),
 ('Santiago', 'Sun', (4, 52)),
 ('Anchorage', 'Sat', (23, 52)),
 ('Ankara', 'Sun', (10, 52)),
 ('Lisbon', 'Sun', (7, 52)),
 ('S찾o Paulo', 'Sun', (5, 52)),
 ('Dubai', 'Sun', (11, 52)),
 ('London', 'Sun', (7, 52)),
 ('Seattle', 'Sun', (0, 52)),
 ('Dublin', 'Sun', (7, 52)),
 ('Los Angeles', 'Sun', (0, 52)),
 ('Athens', 'Sun', (9, 52)),
 ('Edmonton', 'Sun', (1, 52)),
 ('Madrid', 'Sun', (8, 52)),
 ('Shanghai', 'Sun', (15, 52)),
 ('Atlanta', 'Sun', (2, 52)),
 ('Frankfurt', 'Sun', (8, 52)),
 ('Singapore', 'Sun', (15, 52)),
 ('Auckland', 'Sun', (20, 52)),


### NUMERICAL OPERATIONS ON NUMPY ARRAYS

In [144]:
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)

In [146]:
v+2

array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ])

In [147]:
v**0.5

array([1.41421356, 1.73205081, 2.81069386, 1.81659021, 2.62678511,
       0.33166248, 3.20936131, 3.591657  ])

In [148]:
list(v+2)

[4.0, 5.0, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]

In [149]:
[i+2 for i in v]

[4.0, 5.0, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]

In [154]:
def func_sum(x):
    return v+2

list(map(func_sum, v))

[array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ]),
 array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ])]

In [155]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A+B)

[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [158]:
print(A*B)

[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [159]:
print(A@B)

[[36. 36. 36.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [160]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))*3
A/B

array([[ 3.66666667,  4.        ,  4.33333333],
       [ 7.        ,  7.33333333,  7.66666667],
       [10.33333333, 10.66666667, 11.        ]])

In [161]:
A**B

array([[ 1331.,  1728.,  2197.],
       [ 9261., 10648., 12167.],
       [29791., 32768., 35937.]])

#### numpy.dot
numpy.dot(a, b, out=None)

In [163]:
np.dot(A, B)

array([[108., 108., 108.],
       [198., 198., 198.],
       [288., 288., 288.]])

In [164]:
A@B

array([[108., 108., 108.],
       [198., 198., 198.],
       [288., 288., 288.]])

In [165]:
A.dot(B)

array([[108., 108., 108.],
       [198., 198., 198.],
       [288., 288., 288.]])

In [169]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,2))*3
A.dot(B)

array([[108., 108.],
       [198., 198.],
       [288., 288.]])

In [170]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,2))*3
B.dot(A)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [171]:
import numpy as np
X = np.array( [[[3, 1, 2],
                [4, 2, 2],
                [2, 4, 1]],
                [[3, 2, 2],
                [4, 4, 3],
                [4, 1, 1]],
                [[2, 2, 1],
                [3, 1, 3],
                [3, 2, 3]]])
Y = np.array( [[[2, 3, 1],
                [2, 2, 4],
                [3, 4, 4]],
                [[1, 4, 1],
                [4, 1, 2],
                [4, 1, 2]],
                [[1, 2, 3],
                [4, 1, 1],
                [3, 1, 4]]])

In [172]:
X.shape

(3, 3, 3)

In [173]:
Y.shape

(3, 3, 3)

In [178]:
Z = X.dot(Y)

print(Z.shape)
print(Z.ndim)

(3, 3, 3, 3)
4


In [180]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))*3


MA = np.mat(A)
MB = np.mat(B)
print(MA)
print(MB)
print(MA*MB)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[108. 108. 108.]
 [198. 198. 198.]
 [288. 288. 288.]]


#### 비교 연산

In [181]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])
A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [182]:
[ [11, 12, 13], [21, 22, 23], [31, 32, 33] ] == [ [11, 102, 13], [201, 22, 203], [31, 32, 303] ]

False

In [184]:
np.array_equal(A, B)

False

In [185]:
a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])

In [187]:
a > b

array([[False,  True],
       [False, False]])

In [188]:
np.logical_or(a,b)

array([[ True,  True],
       [ True, False]])

In [189]:
np.logical_xor(a,b)

array([[False,  True],
       [ True, False]])

### NUMPY ARRAYS: CONCATENATING, FLATTENING AND ADDING DIMENSIONS

#### FLATTEN

In [190]:
A = np.array([[[ 0, 1],
                [ 2, 3],
                [ 4, 5],
                [ 6, 7]],
                [[ 8, 9],
                [10, 11],
                [12, 13],
                [14, 15]],
                [[16, 17],
                [18, 19],
                [20, 21],
                [22, 23]]])
A.shape

(3, 4, 2)

In [191]:
Flatten_X = A.flatten()
Flatten_X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### RAVEL

In [192]:
Ravel_X = A.ravel()
Ravel_X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Flatten vs Ravel

In [195]:
a = np.random.randint(0, 10, (2,3))
a

array([[9, 0, 5],
       [2, 1, 6]])

In [197]:
print(f'변경 전 :{a}')
b = a.flatten()
b[0] = 10

print(f'변경 후 : {a}')
print(f'b : {b}')

변경 전 :[[9 0 5]
 [2 1 6]]
변경 후 : [[9 0 5]
 [2 1 6]]
b : [10  0  5  2  1  6]


In [198]:
print(f'변경 전 :{a}')
b = a.ravel()
b[0] = 10

print(f'변경 후 : {a}')
print(f'b : {b}')

변경 전 :[[9 0 5]
 [2 1 6]]
변경 후 : [[10  0  5]
 [ 2  1  6]]
b : [10  0  5  2  1  6]


#### Reshape
* numpy.reshape(a, newshape, order='C')


In [199]:
arr = np.array([[0, 1],
       [2, 3],
       [4, 5]])

In [203]:
np.reshape(arr, (5,1))

ValueError: cannot reshape array of size 6 into shape (5,1)

In [202]:
np.reshape(arr, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [207]:
x = np.array(range(24))

In [208]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [211]:
k = x.reshape(2,3,2,2)
k.ndim

4

In [214]:
x = np.array(range(48))
x.reshape(4,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [215]:
x = np.array(range(80))
x.reshape(10,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71]],

       [[72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [216]:
arr_data = arr.reshape((2, 3))
arr_data

array([[0, 1, 2],
       [3, 4, 5]])

In [217]:
arr_data.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [218]:
arr_data.reshape(1, -1)

array([[0, 1, 2, 3, 4, 5]])

#### CONCATENATING ARRAYS
* numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

In [220]:
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])
np.concatenate((x, y, z), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [221]:
x = np.array(range(24))
x = x.reshape((3,4,2))
y = np.array(range(100,124))
y = y.reshape((3,4,2))

In [222]:
print(x)
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[116 117]
  [118 119]
  [120 121]
  [122 123]]]


In [224]:
np.concatenate((x, y), axis = 1)

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [100, 101],
        [102, 103],
        [104, 105],
        [106, 107]],

       [[  8,   9],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [108, 109],
        [110, 111],
        [112, 113],
        [114, 115]],

       [[ 16,  17],
        [ 18,  19],
        [ 20,  21],
        [ 22,  23],
        [116, 117],
        [118, 119],
        [120, 121],
        [122, 123]]])

#### ADDING NEW DIMENSIONS

In [225]:
x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]
print(y)

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


#### VECTOR STACKING


In [226]:
A = np.array([3, 4, 5])
B = np.array([1,9,0])

In [228]:
np.column_stack((A, B))

array([[3, 1],
       [4, 9],
       [5, 0]])

#### NUMPY: BOOLEAN INDEXING

In [231]:
x = np.array([2,5,18,18,18, 18, 14,4])
(x == 18).sum()

4

#### FANCY INDEXING

In [232]:
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])
A <= 5

array([ True, False,  True, False, False, False,  True])

In [233]:
C[[ True, False,  True, False, False, False,  True]]

array([123, 190, 100])

#### WEIGHTED RANDOM CHOICE WITH NUMPY

In [265]:
from numpy.random import choice
professions = ["scientist",
"philosopher",
"engineer",
"priest",
"programmer"]
probabilities = [0.2, 0.05, 0.3, 0.15, 0.3]
choice(professions, p=probabilities)

'scientist'

In [266]:
programming_languages = ["Java", "C", "Python", "C++"]
weights = np.array([16, 15.2, 10, 6.1])
# normalization
weights /= sum(weights)
print(weights)
for i in range(10):
    print(choice(programming_languages, p=weights))

[0.33826638 0.32135307 0.21141649 0.12896406]
Python
Java
C++
Python
Python
Java
Java
Java
C
Java
