In [10]:
import numpy as np
import pandas as pd

#### CREATE DATA 

In [10]:
df = pd.DataFrame(data = np.arange(18).reshape(6,3),
				  index = ['a','b','c','d','e','f'],
                  columns=['col1','col2','col3'])
                  
df['col4'] = pd.Series(data = [1.7, 1.2, 2.4], 
                       index = ['a','e','c'])
df.loc['c'] = None
print('Sample Data')
print(df)

Sample Data
   col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
c   NaN   NaN   NaN   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN


#### MISSING VALUE

In [4]:
print('\n#1 Summary of DataFrame')
print(df.info())

print('\n#2 isnull of DataFrame')
print(df.isnull())

print('\n#4 Sum of all missing values per columns')
print(df.isnull().sum())

print('\n#5 Sum of all missing values per rows')
print(df.isnull().sum(axis=1))


#1 Summary of DataFrame
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    5 non-null      float64
 1   col2    5 non-null      float64
 2   col3    5 non-null      float64
 3   col4    2 non-null      float64
dtypes: float64(4)
memory usage: 412.0+ bytes
None

#2 isnull of DataFrame
    col1   col2   col3   col4
a  False  False  False  False
b  False  False  False   True
c   True   True   True   True
d  False  False  False   True
e  False  False  False  False
f  False  False  False   True

#4 Sum of all missing values per columns
col1    1
col2    1
col3    1
col4    4
dtype: int64

#5 Sum of all missing values per rows
a    0
b    1
c    4
d    1
e    0
f    1
dtype: int64


In [8]:
print(df.dropna())

   col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
e  12.0  13.0  14.0   1.2


In [11]:
print(df.dropna(axis = 1))

Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f]


In [13]:
df.dropna(how = 'all')

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN

In [14]:
df.dropna(how = 'all', axis = 1)

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
c   NaN   NaN   NaN   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN

In [15]:
df.fillna(1)

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   1.0
c   1.0   1.0   1.0   1.0
d   9.0  10.0  11.0   1.0
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   1.0

In [17]:
replace_set = {'col1':df['col1'].max()}
df.fillna(replace_set, inplace = False)

col1  col2  col3  col4
a   0.0   1.0   2.0   1.7
b   3.0   4.0   5.0   NaN
c  15.0   NaN   NaN   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   1.2
f  15.0  16.0  17.0   NaN

### DATA ENCODING

In [20]:
from sklearn.preprocessing import LabelEncoder

#### sklearn.preprocessing.LabelEncoder

* fit(y) => Fit label encoder.

* fit_transform(y) => Fit label encoder and return encoded labels.

* get_metadata_routing() => Get metadata routing of this object.

* get_params([deep]) => Get parameters for this estimator.

* inverse_transform(y) => Transform labels back to original encoding.

* set_output(*[, transform]) => Set output container.

* set_params(**params) => Set the parameters of this estimator.

* transform(y) => Transform labels to normalized encoding.

In [21]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [22]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [23]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### sklearn.preprocessing.OneHotEncoder
* fit(X[, y]) => Fit OneHotEncoder to X.

* fit_transform(X[, y]) => Fit to data, then transform it.

* get_feature_names_out([input_features]) => Get output feature names for transformation.

* get_metadata_routing() => Get metadata routing of this object.

* get_params([deep]) => Get parameters for this estimator.

* inverse_transform(X) => Convert the data back to the original representation.

* set_output(*[, transform]) => Set output container.

* set_params(**params) => Set the parameters of this estimator.

* transform(X) => Transform X using one-hot encoding.

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
labels = labels.reshape(-1, 1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


#### Pandas Encoding

*
pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)

In [38]:
df = pd.DataFrame({'item': ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0     True     False    False     False      False     False
1    False      True    False     False      False     False
2    False     False    False     False       True     False
3    False     False    False     False      False      True
4    False     False    False      True      False     False
5    False     False    False      True      False     False
6    False     False     True     False      False     False
7    False     False     True     False      False     False

#### FEATURE SCALING

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data= iris_data, columns=iris.feature_names)

In [2]:
print('feature 들의 평균값')
print(iris_df.mean())

feature 들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64


In [4]:
print('feature 들의 분산 값')
print(iris_df.var())

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print('feature 들의 평균값')
print(iris_df_scaled.mean())
print('feature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print('feature 들의 최소 값')
print(iris_df_scaled.min())
print('feature 들의 최대 값')
print(iris_df_scaled.max())

feature 들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
